name: s3 workflow

on: workflow_dispatch

jobs:
  terraform:
    name: 'Terraform s3'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Actions'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.3

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-central-1

      - name: 'Terraform Init'
        run: terraform init
        working-directory: ./modules/s3

      - name: 'Terraform Format'
        run: terraform fmt --check
        working-directory: ./modules/s3

      - name: 'Terraform Validate'
        run: terraform validate
        working-directory: ./modules/s3

      - name: 'Terraform Plan'
        env:
          GIT_SHA: ${{ github.sha }}
        run: terraform plan -var="git_sha=${{ github.sha }}"
        working-directory: ./modules/s3

      - name: 'Terraform Apply'
        env:
            GIT_SHA: ${{ github.sha }}
        run: terraform apply -var="git_sha=${{ github.sha }}" -auto-approve
        working-directory: ./modules/s3

      - name: 'Save S3 Bucket Name'
        id: s3_bucket_output
        run: echo "s3_bucket=$(terraform output -raw aws_s3_bucket)" >> $GITHUB_ENV
        working-directory: ./modules/s3

      - name: 'Write S3 Bucket Name to File'
        run: echo ${{ env.s3_bucket }} > s3_bucket_name.txt
    
      - name: 'Upload S3 Bucket Name as Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: s3-bucket-name
          path: s3_bucket_name.txt
      

      
